MONARC is composed of two main parts:

* a back office: for the management of entities and users;
* a front office.


====
TODO: Add a simple schema about the architecture used by Conostix (with the 3 servers,
reverse proxy, etc.)
====

It is possible to connect many front offices to one back office.
A front office instance can be used without the back office.


.Summary of the different modules of the project
[cols="h,a,a"]
|===
|| Back office | Front office

|
| NOTE: Creation of users and instances.
| NOTE: Risk analysis.

| Modules
| * MonarcCore ({uri-zm-core}[zm-core] in vendor/monarc/core)
  * MonarcBO ({uri-zm-backoffice}[zm-backoffice] in vendor/monarc/backoffice)
| * MonarcCore ({uri-zm-core}[zm-core] in vendor/monarc/core)
  * MonarcFO ({uri-zm-client}[zm-client] in vendor/monarc/frontoffice)

| Interfaces
| * {uri-ng-anr}[ng_anr]
  * {uri-ng-backoffice}[ng_backoffice]
| * {uri-ng-anr}[ng_anr]
  * {uri-ng-client}[ng_client]
|===



MonarcCore ({uri-zm-core}[zm-core]) is the API in charge of providing an access
to the data.
MonarcFO ({uri-zm-client}[zm-client]) is the interface for the front-office.
MonarcBO ({uri-zm-client}[zm-backoffice]) is the interface for the back-office.

=== Back end

=== Front end
