=== Requirements

==== Network

The deployment on the different servers requires an Internet connection since
the updates are retrieved from our GitHub repositories. If this is hardly
possible in your environment you need to configure a proxy in order to access
to Internet. This is an important requirement since all MONARC updates,
including security updates, are provided from the Git repositories.

Our link:https://github.com/monarc-project/ansible-ubuntu[ansible playbook]
also needs an Internet connection in order to dynamically deploy new clients.


==== TLS certificate

Is is strongly advised to use a TLS certificate on the reverse proxy. Depending
on your configuration, you may need to secure the connection after the reverse
proxy (see <<monarc-architecture-schema,the global architecture>>).

The certificate *yourcert.crt* and the key file *yourcert.key* are by default
located at ``/etc/sslkeys/`` (location configurable using the variables in the
``inventory/hosts`` file of the ansible playbook). You can also use a single
*.pem* file, but make sure it includes the certificate and the key.


==== System and software

The deployment of MONARC has been tested on Ubuntu 16.04 LTS and Ubuntu 17.04.

* Git;
* PHP (version 7.0 recommended);
** PHP extensions: xml, mbstring, mysql, zip, unzip, mcrypt, intl, gettext,
imagick, ssl
** PHP libraries are managed with composer;
* JavaScript libraries are managed with npm;
* Apache 2;
* MariaDB;
* Postfix (SMTP is used for the account creation and password recovery).


=== Deployment

==== Only the front office

===== Prepared virtual machine

A
link:https://github.com/monarc-project/MonarcAppFO/releases/latest[virtual machine]
for use with VirtualBox is available if you want to quickly test MONARC.

The best way if you want to try an up-to-date version of MONARC.

===== Manual deployment

Follow the instructions
link:https://github.com/monarc-project/MonarcAppFO/tree/master/INSTALL[here].


==== The back office and the front office

The whole architecture can be deployed with
link:https://www.ansible.com[ansible]. More information
link:https://github.com/monarc-project/ansible-ubuntu[here].
