=== Requirements

The deployment of MONARC has been tested on Debian 9.0, Ubuntu 16.04 LTS and
Ubuntu 17.04.

* PHP (version 7.0 recommended);
** PHP extensions: xml, mbstring, mysql, zip, unzip, mcrypt, intl, gettext,
imagick
* Apache 2;
* MariaDB;
* Postfix (SMTP is used for the password recovery).


=== Deployment

==== Only the front office

Different methods are provided.

===== Prepared virtual machine

A
link:https://github.com/monarc-project/MonarcAppFO/releases/latest[virtual machine]
for use with VirtualBox is available if you want to quickly test MONARC.

The best way if you want to try an up-to-date version of MONARC.

===== Vagrant

If you want to deploy the application with Vagrant:

[source,bash]
----
$ sudo apt-get install virtualbox vagrant
$ git clone https://github.com/monarc-project/MonarcAppFO-vagrant.git
$ cd MonarcAppFO-vagrant/
$ vagrant up
----

Once the virtual machine will be ready go to the address:
http://127.0.0.1:5001 +
The username is _admin@admin.test_ and the password is _admin_.

This method is not recommended for production.


===== Manual deployment

Follow the instructions
link:https://github.com/monarc-project/MonarcAppFO/tree/master/INSTALL[here].


==== The back office and the front office

The whole architecture can be deployed with
link:https://www.ansible.com[ansible]. More information
link:https://github.com/monarc-project/ansible-ubuntu[here].
