== Requirements

=== System and software

The deployment of MONARC has been tested on Ubuntu 16.04 LTS and Ubuntu 18.04 LTS.

* Git;
* PHP (version 7.1 or 7.2):
** PHP libraries are managed with link:https://getcomposer.org[composer];
* Node.js:
** JavaScript libraries are managed with link:https://www.npmjs.com[npm];
* Apache 2;
* MariaDB;
* Postfix (SMTP is used for the account creation and password recovery).


=== Specifications by server

.Minimum requirements
[cols="h,a,a,a,a"]
|===
| ^| Back office ^|MONARC ^|Reverse proxy ^|Configuration server

| Number of vCPU
^| 2
^| 2
.3+| Not that powerful.

But all connections (for the BO and FOs) will go through it.
.3+| Not that powerful.

Mainly used for the creation of clients on the different FOs.

| RAM (GB)
^| 2
^| 4

| HDD (GB)
^| 20
^| 20


| Operating System
| Ubuntu Server 18.04 LTS
| Ubuntu Server 18.04 LTS
| Ubuntu Server 18.04 LTS
| Ubuntu Server 18.04 LTS

|===

Of course these values are minimum requirements. MONARC can be installed
on a Raspberry Pi.
It is always better to forecast more memory and disk space for MONARC
(front office) since it will host the data of the analysis.


=== Network

The deployment on the different servers requires an Internet connection since
the updates are retrieved from our GitHub repositories. If this is hardly
possible in your environment due to an internal policy, you need to configure a
proxy in order to access to Internet. This is an important requirement since all
MONARC updates, including security updates, are provided from the Git
repositories.

The link:https://github.com/monarc-project/ansible-ubuntu[ansible playbook]
also needs an Internet connection in order to dynamically deploy new clients.

The servers (or the proxy) should be able to contact:

* github.com
* api.github.com
* pypi.python.org
* registry.npmjs.org
* deb.nodesource.com
* getcomposer.org
* .packagist.org
* packagist.phpcomposer.com
* letsencrypt.org
* APT repositories


To make the different servers use the proxy, specify the address of your proxy
in the file ``/home/ansible/.bash_profile``. For example:

[source,bash]
----
export http_proxy=http://proxy.your.domain.com:4128
export https_proxy=http://proxy.your.domain.com:4128
----

=== TLS certificate

Is is strongly advised to use a TLS certificate on the reverse proxy.
See <<TLS-certificate,this section>>.

The certificate *yourcert.crt* and the key file *yourcert.key* are by default
located at ``/etc/sslkeys/`` (location configurable using the variables in the
``inventory/hosts`` file of the ansible playbook). You can also use a single
*.pem* file, but make sure it includes the certificate and the key.
