=== System

Keep the software of your distribution up-to-date (Apache, PHP, MariaDB, etc.).
At least the security updates from the GNU/Linux distribution.


=== MONARC

The master branch should always be working and it is recommended to install
the project using this one.

If you have already installed MONARC and want to upgrade to a later version, you
can use the provided script:


[source,bash]
----
$ scripts/update-all.sh
$ sudo systemctl restart apache2
----

This script will retrieve the updates from the last stable release of MONARC.


For more details the script will:

* backup your databases in case the upgrade fails;
* check the presence of composer;
* retrieve the new code from the Git repositories from the last stable release:
** pull updates for module/[MonarcCore, MonarcBO/MonarcFO];
** pull updates for node_modules/[ng_anr, ng_backoffice/ng_client].
* run the appropriate database upgrade scripts (pathCore, pathBO, pathFO);
* install/update JavaScript libraries with npm;
* update the translations.
